=== roscopecoltran/etcdrest/examples/ntp/ntp_schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "NTP configuration",
	"definitions": {
		"boolean": {
			"type": "string",
			"enum": [ "true", "false" ]
		},
		"filepath": {
			"type": "string",
			"pattern": "^(.+)/([^/]+)$"
		}
	},
	"type": "object",
	"required": [ "servers", "driftfile" ],
	"additionalProperties": false,
	"properties": {
		"servers": {
			"type": "object",
			"additionalProperties": false,
			"patternProperties": {
				"^[a-z0-9-.]+$": {
					"type": "object",
					"required": [ "options" ],
					"additionalProperties": false,
					"properties": {
						"options": {
							"type": "string"
						}
					}
				}
			}
		},
		"driftfile": {
			"$ref": "#/definitions/filepath"
		},
		"enable_stats": {
			"$ref": "#/definitions/boolean"
		},
		"statsdir": {
			"$ref": "#/definitions/filepath"
		},
		"statistics": {
			"type": "string"
		}
	}
}

=== roscopecoltran/etcdrest/examples/ntp/ntp-site2.json
{
    "servers": {
		"ntp1.site2.example.com": {
			"options": "minpoll 3 maxpoll 7"
		},
		"ntp2.site2.example.com": {
			"options": "minpoll 3 maxpoll 7"
		},
		",ntp3.site2.example.com": {
			"options": "minpoll 3 maxpoll 7"
		}
    },
    "driftfile": "/var/lib/ntp/drift",
    "enable_stats": "true",
    "statsdir": "/var/log/ntpstats/",
    "statistics": "loopstats peerstats"
}
