=== roscopecoltran/etcdrest/static/schemas/host.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "additionalProperties": false,
    "definitions": {
            "boolean": {
                "enum": [
                    "true",
                    "false"
                ],
                "type": "string"
            },
            "hwaddr": {
                "pattern": "^([0-9a-f]{2}:){5}[0-9]{2}$",
                "type": "string"
            },
            "ipv4": {
                "pattern": "^([0-9]{1,3}\\.){3}[0-9]{1,3}$",
                "type": "string"
        }
    },
    "properties": {
        "build": {
            "$ref": "#/definitions/boolean"
        },
        "debug": {
            "$ref": "#/definitions/boolean"
        },
        "gpt": {
            "$ref": "#/definitions/boolean"
        },
        "image": {
            "pattern": "^.+$",
            "type": "string"
        },
        "interfaces": {
            "patternProperties": {
                ".+": {
                    "properties": {
                        "gw": {
                            "$ref": "#/definitions/ipv4"
                        },
                        "hwaddr": {
                            "$ref": "#/definitions/hwaddr"
                        },
                        "ip": {
                            "$ref": "#/definitions/ipv4"
                        },
                        "netmask": {
                            "$ref": "#/definitions/ipv4"
                        }
                    },
                    "additionalProperties": false,
                    "type": "object"
                }
            },
            "type": "object"
        },
        "kexec": {
            "$ref": "#/definitions/boolean"
        },
        "kopts": {
            "type": "string"
        },
        "site": {
            "pattern": "^[a-z][a-z0-9]+$",
            "type": "string"
        },
        "version": {
            "pattern": "^([a-z0-9]{7}|latest)$",
            "type": "string"
        }
    },
    "required": [
        "build",
        "debug",
        "gpt",
        "image",
        "kexec",
        "kopts",
        "site",
        "version"
    ],
    "title": "Host Schema",
    "type": "object"
}

=== roscopecoltran/etcdrest/test/test.json
{
    "build": "false",
    "debug": "false",
    "gpt": "false",
    "image": "centos7.0",
    "interfaces": {
        "eth0": {
            "gw": "11.12.13.14",
            "hwaddr": "00:1a:bc:0a:1a:35",
            "ip": "11.12.13.14",
            "netmask": "255.255.255.0"
        }
    },
    "kexec": "false",
    "kopts": "None",
    "site": "abc1",
    "version": "latest"
}
